export const LANDING = '/';
// export const SIGN_UP = '/signup';
// export const SIGN_IN = '/signin';
export const HOME = '/home'; // recommend friend page
export const FRIEND_REQUESTS = '/home/friend-requests';
export const MY_FRIEND = '/home/my-friend';
export const ACCOUNT = '/account';
export const MESSAGE = '/message';
export const PROFILE = '/profile';
export const EDIT = '/profile/edit';
// export const PASSWORD_FORGET = '/pw-forget';